config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "pages#index"

  resources :posts do
  	resources :postcomments
  end	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments
	validates :title,:body, presence: true
	validates :title, length: { in: 3..10 }
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :postcomments
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :divise_sign_up_params, if: :devise_controller?
	protect_from_forgery with: :exception

private

	def divise_sign_up_params
		devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :nickname,:avatar])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	pp @posts = Post.all
  end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
before_action :authenticate_user!

  def create
  	params[:postcomment][:post_id] = params[:post_id]
  	params[:postcomment][:user_id] = current_user.id
		@comment = Postcomment.create(comment_params)
		   if @comment.save
		      redirect_to post_path(params[:post_id])
		      else
		       @comment.errors.full_messages.each do |msg|
		          @msg = msg
		      end
		      flash[:notice] = "#{@msg}"
		      redirect_to post_path(params[:post_id])
		    end
  end

private

	def comment_params
		params.require(:postcomment).permit(:post_id, :user_id, :comment)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :set_post, only:[:show, :edit, :update, :destroy]

  def show
    pp @comment = @post.postcomments
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		redirect_to root_path
  	else 
  	render 'new'	
  	end	
  		
  end

  def edit

  end

  def update
  	@post.update(post_params)
  	redirect_to root_path
  end

  def destroy
  	@post.destroy
  	redirect_to root_path
  end

private

	def post_params
		params.require(:post).permit(:user_id, :title, :body)
	end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.nil? %>
      <li>
        <%= link_to new_user_session_path do %>
          <i class="glyphicon glyphicon-user"></i></span> Login
          <% end %>
      <li>
        <% else %>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="glyphicon glyphicon-log-out"></i></span> Logout
          <% end %>
      <li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%=render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= link_to "Create New Post", new_post_path , class: "btn btn-default"%>

<% @posts.each do |post| %>
	<h1><%= link_to post.title , post_path(post.id)%></h1>
	<p>
    <%= image_tag post.user.avatar.url, width: 30, height: 30 %>
		Autor:<%= post.user.nickname %> |
		Creeated at:<%= post.created_at %>
		Update at:<%= post.updated_at %>
	</p>
	<p><%= post.body %></p>
	<% if current_user != nil and current_user.id == post.user_id %>
		<%= link_to "Edit", edit_post_path(post.id) %>
		<%= link_to "Delete", post_path(post.id), data: {confim: 'Are you sure?'}, method: :delete %>
	<% end %>
<% end %>

app/views/postcomments/new.html.erb
<h1>Postcomments#new</h1>
<p>Find me in app/views/postcomments/new.html.erb</p>

app/views/posts/_form.html.erb
	<p><%= f.label :title %></p>
	<%= f.text_field :title %><br/>

	<p><%= f.label :body %></p>
	<%= f.text_area :body, cols: 40,rows: 10 %><br/>

	<p><%= f.submit "Save" %></p>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path, method: :patch do |f|%>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
<% end %>

<%= render 'posts/form' , f:f %>

<% end %>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f|%>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
<% end %>

<%= render 'posts/form' , f:f %>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
	Autor:<%= @post.user.nickname %> |
	Creeated at:<%= @post.created_at %> |
	Update at:<%= @post.updated_at %>
</p>
<p><%= @post.body %></p>

<% @comment.each do |comment| %>
<hr>
  <%= image_tag comment.user.avatar.url, width: 30, height: 30 %>
<p>User <b><%= comment.user.nickname %></b> say: </p>
<p><%= comment.comment %></p>
<hr>
<% end %>

<%= form_for :postcomment ,url: post_postcomments_path(@post.id), method: :post do |f| %>
  <% if flash[:notice] %>
    	<div class="notice"><%= flash[:notice] %></div>
    <% end %>
	<p><%= f.label "Add your comment" %></p>
	<p><%= f.text_area :comment, cols: 5,rows: 5 %></p>
	<%= f.submit "Add Comment" %>
<% end %>	

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>